/* File: TriangulatedBoundaryConditionsmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Apr 26 11:32:23 2012
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *TriangulatedBoundaryConditions_error;
static PyObject *TriangulatedBoundaryConditions_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(TriangulatedBoundaryConditions_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = TriangulatedBoundaryConditions_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = TriangulatedBoundaryConditions_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** WallReflect ********************************/
static char doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_WallReflect[] = "\
Function signature:\n\
  WallReflect = WallReflect(point,normal,vertices,dim)\n\
Required arguments:\n"
"  point : input rank-1 array('d') with bounds (21)\n"
"  normal : input rank-1 array('d') with bounds (3)\n"
"  vertices : input rank-2 array('d') with bounds (3,3)\n"
"  dim : input int\n"
"Return objects:\n"
"  WallReflect : rank-1 array('d') with bounds (21)";
/* #declfortranroutine# */
static PyObject *f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_WallReflect(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *WallReflect = NULL;
  npy_intp WallReflect_Dims[1] = {-1};
  const int WallReflect_Rank = 1;
  PyArrayObject *capi_WallReflect_tmp = NULL;
  int capi_WallReflect_intent = 0;
  double *point = NULL;
  npy_intp point_Dims[1] = {-1};
  const int point_Rank = 1;
  PyArrayObject *capi_point_tmp = NULL;
  int capi_point_intent = 0;
  PyObject *point_capi = Py_None;
  double *normal = NULL;
  npy_intp normal_Dims[1] = {-1};
  const int normal_Rank = 1;
  PyArrayObject *capi_normal_tmp = NULL;
  int capi_normal_intent = 0;
  PyObject *normal_capi = Py_None;
  double *vertices = NULL;
  npy_intp vertices_Dims[2] = {-1, -1};
  const int vertices_Rank = 2;
  PyArrayObject *capi_vertices_tmp = NULL;
  int capi_vertices_intent = 0;
  PyObject *vertices_capi = Py_None;
  int dim = 0;
  PyObject *dim_capi = Py_None;
  static char *capi_kwlist[] = {"point","normal","vertices","dim",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.WallReflect",\
    capi_kwlist,&point_capi,&normal_capi,&vertices_capi,&dim_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable dim */
    f2py_success = int_from_pyobj(&dim,dim_capi,"TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.WallReflect() 4th argument (dim) can't be converted to int");
  if (f2py_success) {
  /* Processing variable normal */
  normal_Dims[0]=3;
  capi_normal_intent |= F2PY_INTENT_IN;
  capi_normal_tmp = array_from_pyobj(PyArray_DOUBLE,normal_Dims,normal_Rank,capi_normal_intent,normal_capi);
  if (capi_normal_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 2nd argument `normal' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.WallReflect to C/Fortran array" );
  } else {
    normal = (double *)(capi_normal_tmp->data);

  /* Processing variable WallReflect */
  WallReflect_Dims[0]=21;
  capi_WallReflect_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_WallReflect_tmp = array_from_pyobj(PyArray_DOUBLE,WallReflect_Dims,WallReflect_Rank,capi_WallReflect_intent,Py_None);
  if (capi_WallReflect_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `WallReflect' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.WallReflect to C/Fortran array" );
  } else {
    WallReflect = (double *)(capi_WallReflect_tmp->data);

  /* Processing variable point */
  point_Dims[0]=21;
  capi_point_intent |= F2PY_INTENT_IN;
  capi_point_tmp = array_from_pyobj(PyArray_DOUBLE,point_Dims,point_Rank,capi_point_intent,point_capi);
  if (capi_point_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 1st argument `point' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.WallReflect to C/Fortran array" );
  } else {
    point = (double *)(capi_point_tmp->data);

  /* Processing variable vertices */
  vertices_Dims[0]=3,vertices_Dims[1]=3;
  capi_vertices_intent |= F2PY_INTENT_IN;
  capi_vertices_tmp = array_from_pyobj(PyArray_DOUBLE,vertices_Dims,vertices_Rank,capi_vertices_intent,vertices_capi);
  if (capi_vertices_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 3rd argument `vertices' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.WallReflect to C/Fortran array" );
  } else {
    vertices = (double *)(capi_vertices_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(WallReflect,point,normal,vertices,&dim);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_WallReflect_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vertices_tmp!=vertices_capi) {
    Py_XDECREF(capi_vertices_tmp); }
  }  /*if (capi_vertices_tmp == NULL) ... else of vertices*/
  /* End of cleaning variable vertices */
  if((PyObject *)capi_point_tmp!=point_capi) {
    Py_XDECREF(capi_point_tmp); }
  }  /*if (capi_point_tmp == NULL) ... else of point*/
  /* End of cleaning variable point */
  }  /*if (capi_WallReflect_tmp == NULL) ... else of WallReflect*/
  /* End of cleaning variable WallReflect */
  if((PyObject *)capi_normal_tmp!=normal_capi) {
    Py_XDECREF(capi_normal_tmp); }
  }  /*if (capi_normal_tmp == NULL) ... else of normal*/
  /* End of cleaning variable normal */
  } /*if (f2py_success) of dim*/
  /* End of cleaning variable dim */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of WallReflect *****************************/

/***************************** ReflectionOperator *****************************/
static char doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ReflectionOperator[] = "\
Function signature:\n\
  ReflectionOperator = ReflectionOperator(in,normal)\n\
Required arguments:\n"
"  in : input rank-1 array('d') with bounds (3)\n"
"  normal : input rank-1 array('d') with bounds (3)\n"
"Return objects:\n"
"  ReflectionOperator : rank-1 array('d') with bounds (3)";
/* #declfortranroutine# */
static PyObject *f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ReflectionOperator(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *ReflectionOperator = NULL;
  npy_intp ReflectionOperator_Dims[1] = {-1};
  const int ReflectionOperator_Rank = 1;
  PyArrayObject *capi_ReflectionOperator_tmp = NULL;
  int capi_ReflectionOperator_intent = 0;
  double *in = NULL;
  npy_intp in_Dims[1] = {-1};
  const int in_Rank = 1;
  PyArrayObject *capi_in_tmp = NULL;
  int capi_in_intent = 0;
  PyObject *in_capi = Py_None;
  double *normal = NULL;
  npy_intp normal_Dims[1] = {-1};
  const int normal_Rank = 1;
  PyArrayObject *capi_normal_tmp = NULL;
  int capi_normal_intent = 0;
  PyObject *normal_capi = Py_None;
  static char *capi_kwlist[] = {"in","normal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ReflectionOperator",\
    capi_kwlist,&in_capi,&normal_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable in */
  in_Dims[0]=3;
  capi_in_intent |= F2PY_INTENT_IN;
  capi_in_tmp = array_from_pyobj(PyArray_DOUBLE,in_Dims,in_Rank,capi_in_intent,in_capi);
  if (capi_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 1st argument `in' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ReflectionOperator to C/Fortran array" );
  } else {
    in = (double *)(capi_in_tmp->data);

  /* Processing variable ReflectionOperator */
  ReflectionOperator_Dims[0]=3;
  capi_ReflectionOperator_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ReflectionOperator_tmp = array_from_pyobj(PyArray_DOUBLE,ReflectionOperator_Dims,ReflectionOperator_Rank,capi_ReflectionOperator_intent,Py_None);
  if (capi_ReflectionOperator_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `ReflectionOperator' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ReflectionOperator to C/Fortran array" );
  } else {
    ReflectionOperator = (double *)(capi_ReflectionOperator_tmp->data);

  /* Processing variable normal */
  normal_Dims[0]=3;
  capi_normal_intent |= F2PY_INTENT_IN;
  capi_normal_tmp = array_from_pyobj(PyArray_DOUBLE,normal_Dims,normal_Rank,capi_normal_intent,normal_capi);
  if (capi_normal_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 2nd argument `normal' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ReflectionOperator to C/Fortran array" );
  } else {
    normal = (double *)(capi_normal_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(ReflectionOperator,in,normal);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_ReflectionOperator_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_normal_tmp!=normal_capi) {
    Py_XDECREF(capi_normal_tmp); }
  }  /*if (capi_normal_tmp == NULL) ... else of normal*/
  /* End of cleaning variable normal */
  }  /*if (capi_ReflectionOperator_tmp == NULL) ... else of ReflectionOperator*/
  /* End of cleaning variable ReflectionOperator */
  if((PyObject *)capi_in_tmp!=in_capi) {
    Py_XDECREF(capi_in_tmp); }
  }  /*if (capi_in_tmp == NULL) ... else of in*/
  /* End of cleaning variable in */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of ReflectionOperator *************************/

/******************************* MatrixInverse *******************************/
static char doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_MatrixInverse[] = "\
Function signature:\n\
  MatrixInverse = MatrixInverse(in)\n\
Required arguments:\n"
"  in : input rank-2 array('d') with bounds (3,3)\n"
"Return objects:\n"
"  MatrixInverse : rank-2 array('d') with bounds (3,3)";
/* #declfortranroutine# */
static PyObject *f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_MatrixInverse(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *MatrixInverse = NULL;
  npy_intp MatrixInverse_Dims[2] = {-1, -1};
  const int MatrixInverse_Rank = 2;
  PyArrayObject *capi_MatrixInverse_tmp = NULL;
  int capi_MatrixInverse_intent = 0;
  double *in = NULL;
  npy_intp in_Dims[2] = {-1, -1};
  const int in_Rank = 2;
  PyArrayObject *capi_in_tmp = NULL;
  int capi_in_intent = 0;
  PyObject *in_capi = Py_None;
  static char *capi_kwlist[] = {"in",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.MatrixInverse",\
    capi_kwlist,&in_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable MatrixInverse */
  MatrixInverse_Dims[0]=3,MatrixInverse_Dims[1]=3;
  capi_MatrixInverse_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_MatrixInverse_tmp = array_from_pyobj(PyArray_DOUBLE,MatrixInverse_Dims,MatrixInverse_Rank,capi_MatrixInverse_intent,Py_None);
  if (capi_MatrixInverse_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `MatrixInverse' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.MatrixInverse to C/Fortran array" );
  } else {
    MatrixInverse = (double *)(capi_MatrixInverse_tmp->data);

  /* Processing variable in */
  in_Dims[0]=3,in_Dims[1]=3;
  capi_in_intent |= F2PY_INTENT_IN;
  capi_in_tmp = array_from_pyobj(PyArray_DOUBLE,in_Dims,in_Rank,capi_in_intent,in_capi);
  if (capi_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 1st argument `in' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.MatrixInverse to C/Fortran array" );
  } else {
    in = (double *)(capi_in_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(MatrixInverse,in);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_MatrixInverse_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_in_tmp!=in_capi) {
    Py_XDECREF(capi_in_tmp); }
  }  /*if (capi_in_tmp == NULL) ... else of in*/
  /* End of cleaning variable in */
  }  /*if (capi_MatrixInverse_tmp == NULL) ... else of MatrixInverse*/
  /* End of cleaning variable MatrixInverse */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of MatrixInverse ****************************/

/****************************** vectorProjection ******************************/
static char doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_vectorProjection[] = "\
Function signature:\n\
  vectorProjection = vectorProjection(in,normal)\n\
Required arguments:\n"
"  in : input rank-1 array('d') with bounds (3)\n"
"  normal : input rank-1 array('d') with bounds (3)\n"
"Return objects:\n"
"  vectorProjection : rank-1 array('d') with bounds (3)";
/* #declfortranroutine# */
static PyObject *f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_vectorProjection(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *vectorProjection = NULL;
  npy_intp vectorProjection_Dims[1] = {-1};
  const int vectorProjection_Rank = 1;
  PyArrayObject *capi_vectorProjection_tmp = NULL;
  int capi_vectorProjection_intent = 0;
  double *in = NULL;
  npy_intp in_Dims[1] = {-1};
  const int in_Rank = 1;
  PyArrayObject *capi_in_tmp = NULL;
  int capi_in_intent = 0;
  PyObject *in_capi = Py_None;
  double *normal = NULL;
  npy_intp normal_Dims[1] = {-1};
  const int normal_Rank = 1;
  PyArrayObject *capi_normal_tmp = NULL;
  int capi_normal_intent = 0;
  PyObject *normal_capi = Py_None;
  static char *capi_kwlist[] = {"in","normal",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.vectorProjection",\
    capi_kwlist,&in_capi,&normal_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable in */
  in_Dims[0]=3;
  capi_in_intent |= F2PY_INTENT_IN;
  capi_in_tmp = array_from_pyobj(PyArray_DOUBLE,in_Dims,in_Rank,capi_in_intent,in_capi);
  if (capi_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 1st argument `in' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.vectorProjection to C/Fortran array" );
  } else {
    in = (double *)(capi_in_tmp->data);

  /* Processing variable vectorProjection */
  vectorProjection_Dims[0]=3;
  capi_vectorProjection_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_vectorProjection_tmp = array_from_pyobj(PyArray_DOUBLE,vectorProjection_Dims,vectorProjection_Rank,capi_vectorProjection_intent,Py_None);
  if (capi_vectorProjection_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `vectorProjection' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.vectorProjection to C/Fortran array" );
  } else {
    vectorProjection = (double *)(capi_vectorProjection_tmp->data);

  /* Processing variable normal */
  normal_Dims[0]=3;
  capi_normal_intent |= F2PY_INTENT_IN;
  capi_normal_tmp = array_from_pyobj(PyArray_DOUBLE,normal_Dims,normal_Rank,capi_normal_intent,normal_capi);
  if (capi_normal_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 2nd argument `normal' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.vectorProjection to C/Fortran array" );
  } else {
    normal = (double *)(capi_normal_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(vectorProjection,in,normal);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_vectorProjection_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_normal_tmp!=normal_capi) {
    Py_XDECREF(capi_normal_tmp); }
  }  /*if (capi_normal_tmp == NULL) ... else of normal*/
  /* End of cleaning variable normal */
  }  /*if (capi_vectorProjection_tmp == NULL) ... else of vectorProjection*/
  /* End of cleaning variable vectorProjection */
  if((PyObject *)capi_in_tmp!=in_capi) {
    Py_XDECREF(capi_in_tmp); }
  }  /*if (capi_in_tmp == NULL) ... else of in*/
  /* End of cleaning variable in */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of vectorProjection **************************/

/*************************** LeadingEdgePointSearch ***************************/
static char doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_LeadingEdgePointSearch[] = "\
Function signature:\n\
  inda = LeadingEdgePointSearch(nodes_x,faces_x,face_nodes_x,point_in,[num_nodes,num_faces])\n\
Required arguments:\n"
"  nodes_x : input rank-2 array('d') with bounds (3,num_nodes)\n"
"  faces_x : input rank-2 array('d') with bounds (3,num_faces)\n"
"  face_nodes_x : input rank-2 array('i') with bounds (3,num_faces)\n"
"  point_in : input rank-1 array('d') with bounds (21)\n"
"Optional arguments:\n"
"  num_nodes := shape(nodes_x,1) input int\n"
"  num_faces := shape(faces_x,1) input int\n"
"Return objects:\n"
"  inda : int";
/*  */
static PyObject *f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_LeadingEdgePointSearch(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *nodes_x = NULL;
  npy_intp nodes_x_Dims[2] = {-1, -1};
  const int nodes_x_Rank = 2;
  PyArrayObject *capi_nodes_x_tmp = NULL;
  int capi_nodes_x_intent = 0;
  PyObject *nodes_x_capi = Py_None;
  double *faces_x = NULL;
  npy_intp faces_x_Dims[2] = {-1, -1};
  const int faces_x_Rank = 2;
  PyArrayObject *capi_faces_x_tmp = NULL;
  int capi_faces_x_intent = 0;
  PyObject *faces_x_capi = Py_None;
  int *face_nodes_x = NULL;
  npy_intp face_nodes_x_Dims[2] = {-1, -1};
  const int face_nodes_x_Rank = 2;
  PyArrayObject *capi_face_nodes_x_tmp = NULL;
  int capi_face_nodes_x_intent = 0;
  PyObject *face_nodes_x_capi = Py_None;
  double *point_in = NULL;
  npy_intp point_in_Dims[1] = {-1};
  const int point_in_Rank = 1;
  PyArrayObject *capi_point_in_tmp = NULL;
  int capi_point_in_intent = 0;
  PyObject *point_in_capi = Py_None;
  int num_nodes = 0;
  PyObject *num_nodes_capi = Py_None;
  int num_faces = 0;
  PyObject *num_faces_capi = Py_None;
  int inda = 0;
  static char *capi_kwlist[] = {"nodes_x","faces_x","face_nodes_x","point_in","num_nodes","num_faces",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|OO:TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.LeadingEdgePointSearch",\
    capi_kwlist,&nodes_x_capi,&faces_x_capi,&face_nodes_x_capi,&point_in_capi,&num_nodes_capi,&num_faces_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable point_in */
  point_in_Dims[0]=21;
  capi_point_in_intent |= F2PY_INTENT_IN;
  capi_point_in_tmp = array_from_pyobj(PyArray_DOUBLE,point_in_Dims,point_in_Rank,capi_point_in_intent,point_in_capi);
  if (capi_point_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 4th argument `point_in' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.LeadingEdgePointSearch to C/Fortran array" );
  } else {
    point_in = (double *)(capi_point_in_tmp->data);

  /* Processing variable nodes_x */
  nodes_x_Dims[0]=3;
  capi_nodes_x_intent |= F2PY_INTENT_IN;
  capi_nodes_x_tmp = array_from_pyobj(PyArray_DOUBLE,nodes_x_Dims,nodes_x_Rank,capi_nodes_x_intent,nodes_x_capi);
  if (capi_nodes_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 1st argument `nodes_x' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.LeadingEdgePointSearch to C/Fortran array" );
  } else {
    nodes_x = (double *)(capi_nodes_x_tmp->data);

  /* Processing variable faces_x */
  faces_x_Dims[0]=3;
  capi_faces_x_intent |= F2PY_INTENT_IN;
  capi_faces_x_tmp = array_from_pyobj(PyArray_DOUBLE,faces_x_Dims,faces_x_Rank,capi_faces_x_intent,faces_x_capi);
  if (capi_faces_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 2nd argument `faces_x' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.LeadingEdgePointSearch to C/Fortran array" );
  } else {
    faces_x = (double *)(capi_faces_x_tmp->data);

  /* Processing variable inda */
  /* Processing variable num_nodes */
  if (num_nodes_capi == Py_None) num_nodes = shape(nodes_x,1); else
    f2py_success = int_from_pyobj(&num_nodes,num_nodes_capi,"TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.LeadingEdgePointSearch() 1st keyword (num_nodes) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(nodes_x,1)==num_nodes,"shape(nodes_x,1)==num_nodes","1st keyword num_nodes","LeadingEdgePointSearch:num_nodes=%d",num_nodes) {
  /* Processing variable num_faces */
  if (num_faces_capi == Py_None) num_faces = shape(faces_x,1); else
    f2py_success = int_from_pyobj(&num_faces,num_faces_capi,"TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.LeadingEdgePointSearch() 2nd keyword (num_faces) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(faces_x,1)==num_faces,"shape(faces_x,1)==num_faces","2nd keyword num_faces","LeadingEdgePointSearch:num_faces=%d",num_faces) {
  /* Processing variable face_nodes_x */
  face_nodes_x_Dims[0]=3,face_nodes_x_Dims[1]=num_faces;
  capi_face_nodes_x_intent |= F2PY_INTENT_IN;
  capi_face_nodes_x_tmp = array_from_pyobj(PyArray_INT,face_nodes_x_Dims,face_nodes_x_Rank,capi_face_nodes_x_intent,face_nodes_x_capi);
  if (capi_face_nodes_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 3rd argument `face_nodes_x' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.LeadingEdgePointSearch to C/Fortran array" );
  } else {
    face_nodes_x = (int *)(capi_face_nodes_x_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(nodes_x,faces_x,face_nodes_x,point_in,&num_nodes,&num_faces,&inda);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",inda);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_face_nodes_x_tmp!=face_nodes_x_capi) {
    Py_XDECREF(capi_face_nodes_x_tmp); }
  }  /*if (capi_face_nodes_x_tmp == NULL) ... else of face_nodes_x*/
  /* End of cleaning variable face_nodes_x */
  } /*CHECKSCALAR(shape(faces_x,1)==num_faces)*/
  } /*if (f2py_success) of num_faces*/
  /* End of cleaning variable num_faces */
  } /*CHECKSCALAR(shape(nodes_x,1)==num_nodes)*/
  } /*if (f2py_success) of num_nodes*/
  /* End of cleaning variable num_nodes */
  /* End of cleaning variable inda */
  if((PyObject *)capi_faces_x_tmp!=faces_x_capi) {
    Py_XDECREF(capi_faces_x_tmp); }
  }  /*if (capi_faces_x_tmp == NULL) ... else of faces_x*/
  /* End of cleaning variable faces_x */
  if((PyObject *)capi_nodes_x_tmp!=nodes_x_capi) {
    Py_XDECREF(capi_nodes_x_tmp); }
  }  /*if (capi_nodes_x_tmp == NULL) ... else of nodes_x*/
  /* End of cleaning variable nodes_x */
  if((PyObject *)capi_point_in_tmp!=point_in_capi) {
    Py_XDECREF(capi_point_in_tmp); }
  }  /*if (capi_point_in_tmp == NULL) ... else of point_in*/
  /* End of cleaning variable point_in */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*********************** end of LeadingEdgePointSearch ***********************/

/************************** ComputeCompuCoordsDelta **************************/
static char doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputeCompuCoordsDelta[] = "\
Function signature:\n\
  ComputeCompuCoordsDelta = ComputeCompuCoordsDelta(point,metric,jacobian,base_point)\n\
Required arguments:\n"
"  point : input rank-1 array('d') with bounds (3)\n"
"  metric : input rank-1 array('d') with bounds (9)\n"
"  jacobian : input float\n"
"  base_point : input rank-1 array('d') with bounds (3)\n"
"Return objects:\n"
"  ComputeCompuCoordsDelta : rank-1 array('i') with bounds (3)";
/* #declfortranroutine# */
static PyObject *f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputeCompuCoordsDelta(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int *ComputeCompuCoordsDelta = NULL;
  npy_intp ComputeCompuCoordsDelta_Dims[1] = {-1};
  const int ComputeCompuCoordsDelta_Rank = 1;
  PyArrayObject *capi_ComputeCompuCoordsDelta_tmp = NULL;
  int capi_ComputeCompuCoordsDelta_intent = 0;
  double *point = NULL;
  npy_intp point_Dims[1] = {-1};
  const int point_Rank = 1;
  PyArrayObject *capi_point_tmp = NULL;
  int capi_point_intent = 0;
  PyObject *point_capi = Py_None;
  double *metric = NULL;
  npy_intp metric_Dims[1] = {-1};
  const int metric_Rank = 1;
  PyArrayObject *capi_metric_tmp = NULL;
  int capi_metric_intent = 0;
  PyObject *metric_capi = Py_None;
  double jacobian = 0;
  PyObject *jacobian_capi = Py_None;
  double *base_point = NULL;
  npy_intp base_point_Dims[1] = {-1};
  const int base_point_Rank = 1;
  PyArrayObject *capi_base_point_tmp = NULL;
  int capi_base_point_intent = 0;
  PyObject *base_point_capi = Py_None;
  static char *capi_kwlist[] = {"point","metric","jacobian","base_point",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputeCompuCoordsDelta",\
    capi_kwlist,&point_capi,&metric_capi,&jacobian_capi,&base_point_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable point */
  point_Dims[0]=3;
  capi_point_intent |= F2PY_INTENT_IN;
  capi_point_tmp = array_from_pyobj(PyArray_DOUBLE,point_Dims,point_Rank,capi_point_intent,point_capi);
  if (capi_point_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 1st argument `point' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputeCompuCoordsDelta to C/Fortran array" );
  } else {
    point = (double *)(capi_point_tmp->data);

  /* Processing variable metric */
  metric_Dims[0]=9;
  capi_metric_intent |= F2PY_INTENT_IN;
  capi_metric_tmp = array_from_pyobj(PyArray_DOUBLE,metric_Dims,metric_Rank,capi_metric_intent,metric_capi);
  if (capi_metric_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 2nd argument `metric' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputeCompuCoordsDelta to C/Fortran array" );
  } else {
    metric = (double *)(capi_metric_tmp->data);

  /* Processing variable ComputeCompuCoordsDelta */
  ComputeCompuCoordsDelta_Dims[0]=3;
  capi_ComputeCompuCoordsDelta_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ComputeCompuCoordsDelta_tmp = array_from_pyobj(PyArray_INT,ComputeCompuCoordsDelta_Dims,ComputeCompuCoordsDelta_Rank,capi_ComputeCompuCoordsDelta_intent,Py_None);
  if (capi_ComputeCompuCoordsDelta_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `ComputeCompuCoordsDelta' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputeCompuCoordsDelta to C/Fortran array" );
  } else {
    ComputeCompuCoordsDelta = (int *)(capi_ComputeCompuCoordsDelta_tmp->data);

  /* Processing variable jacobian */
    f2py_success = double_from_pyobj(&jacobian,jacobian_capi,"TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputeCompuCoordsDelta() 3rd argument (jacobian) can't be converted to double");
  if (f2py_success) {
  /* Processing variable base_point */
  base_point_Dims[0]=3;
  capi_base_point_intent |= F2PY_INTENT_IN;
  capi_base_point_tmp = array_from_pyobj(PyArray_DOUBLE,base_point_Dims,base_point_Rank,capi_base_point_intent,base_point_capi);
  if (capi_base_point_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 4th argument `base_point' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputeCompuCoordsDelta to C/Fortran array" );
  } else {
    base_point = (double *)(capi_base_point_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(ComputeCompuCoordsDelta,point,metric,&jacobian,base_point);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_ComputeCompuCoordsDelta_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_base_point_tmp!=base_point_capi) {
    Py_XDECREF(capi_base_point_tmp); }
  }  /*if (capi_base_point_tmp == NULL) ... else of base_point*/
  /* End of cleaning variable base_point */
  } /*if (f2py_success) of jacobian*/
  /* End of cleaning variable jacobian */
  }  /*if (capi_ComputeCompuCoordsDelta_tmp == NULL) ... else of ComputeCompuCoordsDelta*/
  /* End of cleaning variable ComputeCompuCoordsDelta */
  if((PyObject *)capi_metric_tmp!=metric_capi) {
    Py_XDECREF(capi_metric_tmp); }
  }  /*if (capi_metric_tmp == NULL) ... else of metric*/
  /* End of cleaning variable metric */
  if((PyObject *)capi_point_tmp!=point_capi) {
    Py_XDECREF(capi_point_tmp); }
  }  /*if (capi_point_tmp == NULL) ... else of point*/
  /* End of cleaning variable point */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*********************** end of ComputeCompuCoordsDelta ***********************/

/***************************** ComputationalGrads *****************************/
static char doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputationalGrads[] = "\
Function signature:\n\
  gradXi,gradEta,gradZeta = ComputationalGrads(Metric,Jac)\n\
Required arguments:\n"
"  Metric : input rank-1 array('d') with bounds (9)\n"
"  Jac : input float\n"
"Return objects:\n"
"  gradXi : rank-1 array('d') with bounds (3)\n"
"  gradEta : rank-1 array('d') with bounds (3)\n"
"  gradZeta : rank-1 array('d') with bounds (3)";
/*  */
static PyObject *f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputationalGrads(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *Metric = NULL;
  npy_intp Metric_Dims[1] = {-1};
  const int Metric_Rank = 1;
  PyArrayObject *capi_Metric_tmp = NULL;
  int capi_Metric_intent = 0;
  PyObject *Metric_capi = Py_None;
  double Jac = 0;
  PyObject *Jac_capi = Py_None;
  double *gradXi = NULL;
  npy_intp gradXi_Dims[1] = {-1};
  const int gradXi_Rank = 1;
  PyArrayObject *capi_gradXi_tmp = NULL;
  int capi_gradXi_intent = 0;
  double *gradEta = NULL;
  npy_intp gradEta_Dims[1] = {-1};
  const int gradEta_Rank = 1;
  PyArrayObject *capi_gradEta_tmp = NULL;
  int capi_gradEta_intent = 0;
  double *gradZeta = NULL;
  npy_intp gradZeta_Dims[1] = {-1};
  const int gradZeta_Rank = 1;
  PyArrayObject *capi_gradZeta_tmp = NULL;
  int capi_gradZeta_intent = 0;
  static char *capi_kwlist[] = {"Metric","Jac",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputationalGrads",\
    capi_kwlist,&Metric_capi,&Jac_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable gradEta */
  gradEta_Dims[0]=3;
  capi_gradEta_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_gradEta_tmp = array_from_pyobj(PyArray_DOUBLE,gradEta_Dims,gradEta_Rank,capi_gradEta_intent,Py_None);
  if (capi_gradEta_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `gradEta' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputationalGrads to C/Fortran array" );
  } else {
    gradEta = (double *)(capi_gradEta_tmp->data);

  /* Processing variable Metric */
  Metric_Dims[0]=9;
  capi_Metric_intent |= F2PY_INTENT_IN;
  capi_Metric_tmp = array_from_pyobj(PyArray_DOUBLE,Metric_Dims,Metric_Rank,capi_Metric_intent,Metric_capi);
  if (capi_Metric_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting 1st argument `Metric' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputationalGrads to C/Fortran array" );
  } else {
    Metric = (double *)(capi_Metric_tmp->data);

  /* Processing variable Jac */
    f2py_success = double_from_pyobj(&Jac,Jac_capi,"TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputationalGrads() 2nd argument (Jac) can't be converted to double");
  if (f2py_success) {
  /* Processing variable gradZeta */
  gradZeta_Dims[0]=3;
  capi_gradZeta_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_gradZeta_tmp = array_from_pyobj(PyArray_DOUBLE,gradZeta_Dims,gradZeta_Rank,capi_gradZeta_intent,Py_None);
  if (capi_gradZeta_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `gradZeta' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputationalGrads to C/Fortran array" );
  } else {
    gradZeta = (double *)(capi_gradZeta_tmp->data);

  /* Processing variable gradXi */
  gradXi_Dims[0]=3;
  capi_gradXi_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_gradXi_tmp = array_from_pyobj(PyArray_DOUBLE,gradXi_Dims,gradXi_Rank,capi_gradXi_intent,Py_None);
  if (capi_gradXi_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(TriangulatedBoundaryConditions_error,"failed in converting hidden `gradXi' of TriangulatedBoundaryConditions.TriangulatedBoundaryConditions.ComputationalGrads to C/Fortran array" );
  } else {
    gradXi = (double *)(capi_gradXi_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(Metric,&Jac,gradXi,gradEta,gradZeta);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNN",capi_gradXi_tmp,capi_gradEta_tmp,capi_gradZeta_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_gradXi_tmp == NULL) ... else of gradXi*/
  /* End of cleaning variable gradXi */
  }  /*if (capi_gradZeta_tmp == NULL) ... else of gradZeta*/
  /* End of cleaning variable gradZeta */
  } /*if (f2py_success) of Jac*/
  /* End of cleaning variable Jac */
  if((PyObject *)capi_Metric_tmp!=Metric_capi) {
    Py_XDECREF(capi_Metric_tmp); }
  }  /*if (capi_Metric_tmp == NULL) ... else of Metric*/
  /* End of cleaning variable Metric */
  }  /*if (capi_gradEta_tmp == NULL) ... else of gradEta*/
  /* End of cleaning variable gradEta */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************* end of ComputationalGrads *************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_TriangulatedBoundaryConditions_def[] = {
  {"WallReflect",-1,{{-1}},0,NULL,(void *)f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_WallReflect,doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_WallReflect},
  {"ReflectionOperator",-1,{{-1}},0,NULL,(void *)f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ReflectionOperator,doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ReflectionOperator},
  {"MatrixInverse",-1,{{-1}},0,NULL,(void *)f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_MatrixInverse,doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_MatrixInverse},
  {"vectorProjection",-1,{{-1}},0,NULL,(void *)f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_vectorProjection,doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_vectorProjection},
  {"LeadingEdgePointSearch",-1,{{-1}},0,NULL,(void *)f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_LeadingEdgePointSearch,doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_LeadingEdgePointSearch},
  {"ComputeCompuCoordsDelta",-1,{{-1}},0,NULL,(void *)f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputeCompuCoordsDelta,doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputeCompuCoordsDelta},
  {"ComputationalGrads",-1,{{-1}},0,NULL,(void *)f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputationalGrads,doc_f2py_rout_TriangulatedBoundaryConditions_TriangulatedBoundaryConditions_ComputationalGrads},
  {NULL}
};

static void f2py_setup_TriangulatedBoundaryConditions(char *WallReflect,char *ReflectionOperator,char *MatrixInverse,char *vectorProjection,char *LeadingEdgePointSearch,char *ComputeCompuCoordsDelta,char *ComputationalGrads) {
  int i_f2py=0;
  f2py_TriangulatedBoundaryConditions_def[i_f2py++].data = WallReflect;
  f2py_TriangulatedBoundaryConditions_def[i_f2py++].data = ReflectionOperator;
  f2py_TriangulatedBoundaryConditions_def[i_f2py++].data = MatrixInverse;
  f2py_TriangulatedBoundaryConditions_def[i_f2py++].data = vectorProjection;
  f2py_TriangulatedBoundaryConditions_def[i_f2py++].data = LeadingEdgePointSearch;
  f2py_TriangulatedBoundaryConditions_def[i_f2py++].data = ComputeCompuCoordsDelta;
  f2py_TriangulatedBoundaryConditions_def[i_f2py++].data = ComputationalGrads;
}
extern void F_FUNC(f2pyinitTriangulatedBoundaryConditions,F2PYINITTRIANGULATEDBOUNDARYCONDITIONS)(void (*)(char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_TriangulatedBoundaryConditions(void) {
  F_FUNC(f2pyinitTriangulatedBoundaryConditions,F2PYINITTRIANGULATEDBOUNDARYCONDITIONS)(f2py_setup_TriangulatedBoundaryConditions);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "TriangulatedBoundaryConditions",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_TriangulatedBoundaryConditions(void) {
#else
#define RETVAL
PyMODINIT_FUNC initTriangulatedBoundaryConditions(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = TriangulatedBoundaryConditions_module = PyModule_Create(&moduledef);
#else
  m = TriangulatedBoundaryConditions_module = Py_InitModule("TriangulatedBoundaryConditions", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module TriangulatedBoundaryConditions (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'TriangulatedBoundaryConditions' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  TriangulatedBoundaryConditions --- WallReflect(),ReflectionOperator(),MatrixInverse(),vectorProjection(),LeadingEdgePointSearch(),ComputeCompuCoordsDelta(),ComputationalGrads()"".");
  PyDict_SetItemString(d, "__doc__", s);
  TriangulatedBoundaryConditions_error = PyErr_NewException ("TriangulatedBoundaryConditions.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));







/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "TriangulatedBoundaryConditions", PyFortranObject_New(f2py_TriangulatedBoundaryConditions_def,f2py_init_TriangulatedBoundaryConditions));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"TriangulatedBoundaryConditions");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
