!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_TriangulatedBoundaryConditions_WallReflect (Wa&
     &llReflectf2pywrap, point, normal, vertices, dim)
      use TriangulatedBoundaryConditions, only : WallReflect
      integer dim
      real(kind=8) point(21)
      real(kind=8) normal(3)
      real(kind=8) vertices(3,3)
      real(kind=8) WallReflectf2pywrap(21)
      WallReflectf2pywrap = WallReflect(point, normal, vertices, dim)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_WallReflect
      subroutine f2pywrap_TriangulatedBoundaryConditions_ReflectionOpera&
     &tor (ReflectionOperatorf2pywrap, in, normal)
      use TriangulatedBoundaryConditions, only : ReflectionOperator
      real(kind=8) in(3)
      real(kind=8) normal(3)
      real(kind=8) ReflectionOperatorf2pywrap(3)
      ReflectionOperatorf2pywrap = ReflectionOperator(in, normal)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_ReflectionO&
     &perator
      subroutine f2pywrap_TriangulatedBoundaryConditions_MatrixInverse (&
     &MatrixInversef2pywrap, in)
      use TriangulatedBoundaryConditions, only : MatrixInverse
      real(kind=8) in(3,3)
      real(kind=8) MatrixInversef2pywrap(3,3)
      MatrixInversef2pywrap = MatrixInverse(in)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_MatrixInver&
     &se
      subroutine f2pywrap_TriangulatedBoundaryConditions_vectorProjectio&
     &n (vectorProjectionf2pywrap, in, normal)
      use TriangulatedBoundaryConditions, only : vectorProjection
      real(kind=8) in(3)
      real(kind=8) normal(3)
      real(kind=8) vectorProjectionf2pywrap(3)
      vectorProjectionf2pywrap = vectorProjection(in, normal)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_vectorProje&
     &ction
      subroutine f2pywrap_TriangulatedBoundaryConditions_ComputeCompuCoo&
     &rdsDelta (ComputeCompuCoordsDeltaf2pywrap, point, metric, jacobian&
     &, base_point)
      use TriangulatedBoundaryConditions, only : ComputeCompuCoordsDelta
      real(kind=8) jacobian
      real(kind=8) point(3)
      real(kind=8) metric(9)
      real(kind=8) base_point(3)
      integer ComputeCompuCoordsDeltaf2pywrap(3)
      ComputeCompuCoordsDeltaf2pywrap = ComputeCompuCoordsDelta(point, m&
     &etric, jacobian, base_point)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_ComputeComp&
     &uCoordsDelta
      
      subroutine f2pyinitTriangulatedBoundaryConditions(f2pysetupfunc)
      use TriangulatedBoundaryConditions, only : LeadingEdgePointSearch
      use TriangulatedBoundaryConditions, only : ComputationalGrads
      interface 
      subroutine f2pywrap_TriangulatedBoundaryConditions_WallReflect (Wa&
     &llReflectf2pywrap, WallReflect, point, normal, vertices, dim)
      integer dim
      real(kind=8) point(21)
      real(kind=8) normal(3)
      real(kind=8) vertices(3,3)
      real(kind=8) WallReflect(21)
      real(kind=8) WallReflectf2pywrap(21)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_WallReflect&
     & 
      subroutine f2pywrap_TriangulatedBoundaryConditions_ReflectionOpera&
     &tor (ReflectionOperatorf2pywrap, ReflectionOperator, in, normal)
      real(kind=8) in(3)
      real(kind=8) normal(3)
      real(kind=8) ReflectionOperator(3)
      real(kind=8) ReflectionOperatorf2pywrap(3)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_ReflectionO&
     &perator 
      subroutine f2pywrap_TriangulatedBoundaryConditions_MatrixInverse (&
     &MatrixInversef2pywrap, MatrixInverse, in)
      real(kind=8) in(3,3)
      real(kind=8) MatrixInverse(3,3)
      real(kind=8) MatrixInversef2pywrap(3,3)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_MatrixInver&
     &se 
      subroutine f2pywrap_TriangulatedBoundaryConditions_vectorProjectio&
     &n (vectorProjectionf2pywrap, vectorProjection, in, normal)
      real(kind=8) in(3)
      real(kind=8) normal(3)
      real(kind=8) vectorProjection(3)
      real(kind=8) vectorProjectionf2pywrap(3)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_vectorProje&
     &ction 
      subroutine f2pywrap_TriangulatedBoundaryConditions_ComputeCompuCoo&
     &rdsDelta (ComputeCompuCoordsDeltaf2pywrap, ComputeCompuCoordsDelta&
     &, point, metric, jacobian, base_point)
      real(kind=8) jacobian
      real(kind=8) point(3)
      real(kind=8) metric(9)
      real(kind=8) base_point(3)
      integer ComputeCompuCoordsDelta(3)
      integer ComputeCompuCoordsDeltaf2pywrap(3)
      end subroutine f2pywrap_TriangulatedBoundaryConditions_ComputeComp&
     &uCoordsDelta
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_TriangulatedBoundaryConditions_WallRef&
     &lect,f2pywrap_TriangulatedBoundaryConditions_ReflectionOperator,f2&
     &pywrap_TriangulatedBoundaryConditions_MatrixInverse,f2pywrap_Trian&
     &gulatedBoundaryConditions_vectorProjection,LeadingEdgePointSearch,&
     &f2pywrap_TriangulatedBoundaryConditions_ComputeCompuCoordsDelta,Co&
     &mputationalGrads)
      end subroutine f2pyinitTriangulatedBoundaryConditions


