
addl_source_dir = "./f90src/"
def configuration(parent_package='',top_path=None,compile_type='debug'):
    from numpy.distutils.misc_util import Configuration
    from os import getcwd
    opts={'debug':'--debug --noopt --noarch','run':'--opt=-O3'}
    config = Configuration('Streamer',parent_package,top_path)
    config.add_extension('Godunov_driver','Godunov_driver.f90',
                         extra_compile_args=['-J./bindings'],
                         include_dirs=['/usr/local/include',
                                       '/usr/include','./bindings'],
                         libraries=['lapack','recipes_f90','minpack','cgns',
                                    'Streamer'],
                         library_dirs=['/usr/local/lib','/usr/lib','.'],
                         extra_link_args=['-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/']
                         )
    config.add_extension("Source_functions",
                         addl_source_dir+'Source_functions.f90',
                         extra_compile_args=['-J./bindings'],
                         include_dirs=['/usr/local/include',
                                       '/usr/include','./bindings'],
                         libraries=['lapack','recipes_f90','minpack','cgns',
                                    'Streamer'],
                         library_dirs=['/usr/local/lib','/usr/lib','.'],
                         extra_link_args=['-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/']
                         )
#    config.add_extension('Godunov',prepend_GU("Godunov.f90"),
#                         extra_compile_args=["-fbounds-check"],
#                         include_dirs=['/usr/local/include','/usr/include','..'],
#                         libraries=['lapack','recipes_f90','minpack'],
#                         library_dirs=['/usr/local/lib','/usr/lib']
#                         )
    config.add_extension('BoundaryConditionsStuff',
                         prepend_GU('BoundaryConditionsStuff.f90'),
                         extra_compile_args=["-fbounds-check"],
                         include_dirs=['/usr/local/include','/usr/include'],
                         libraries=['lapack'],
                         library_dirs=['/usr/local/lib','/usr/lib'],
                         extra_link_args=['-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/']
                         )
    config.add_extension('STLA_IO',addl_source_dir+'stla_io.f90',        
                         extra_compile_args=["-fbounds-check"],
                         include_dirs=['/usr/local/include','/usr/include'],
                         libraries=['lapack'],
                         library_dirs=['/usr/local/lib','/usr/lib'],
                         extra_link_args=['-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/']
                         )
    config.add_extension('TimeAdvancementStuff',
                         prepend_GU('TimeAdvancementStuff.f90'),
                         extra_compile_args=["-fbounds-check"],
                         include_dirs=['/usr/local/include','/usr/include'],
                         libraries=['lapack'],
                         library_dirs=['/usr/local/lib','/usr/lib'],
                         extra_link_args=['-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/']
                         )
    config.add_extension('CGNS_Interface',addl_source_dir+'cgns_interface.f90',
                         include_dirs=['/usr/local/include','/usr/include'],
                         libraries=['cgns','lapack'],
                         library_dirs=['/usr/local/lib','/usr/lib'],
                         extra_compile_args=["-fbounds-check"],
                         extra_link_args=['-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/'])
    return config

def prepend_GU(fin):
    fout_name = addl_source_dir+fin.split('.')[0]+'GU.f90'
    fout = open(fout_name,'w')
    fout.write('''! This file is automatically generated from
! '''+fin.split('x')[0]+''' and from GeneralUtilities.f90
''')
    f=open(addl_source_dir+'GeneralUtilities.f90')
    for line in f:
        fout.write(line)
    f.close()
    f=open(addl_source_dir+fin)
    for line in f:
        fout.write(line)
    f.close()
    fout.close()
    return(fout_name)
    
    

if __name__ == "__main__":
    from numpy.distutils.core import setup
    setup(**configuration(top_path='').todict())
