num=load('1D_Rie_Test_10.dat')
plot(num(:,1),num(:,2),'b.')
hold on
exact=load('exact0.dat')
plot(num(:,1),exact,'b')
num=load('1D_Rie_Test_11.dat')
plot(num(:,1),num(:,2),'g.')
exact=load('exact1.dat')
plot(num(:,1),exact,'g')
num=load('1D_Rie_Test_12.dat')
plot(num(:,1),num(:,2),'r.')
exact=load('exact2.dat')
plot(num(:,1),exact,'r')
num=load('1D_Rie_Test_13.dat')
plot(num(:,1),num(:,2),'c.')
exact=load('exact3.dat')
plot(num(:,1),exact,'c')
num=load('1D_Rie_Test_14.dat')
plot(num(:,1),num(:,2),'k.')
exact=load('exact4.dat')
plot(num(:,1),exact,'k')
hold off
